name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main # Change this if needed

jobs:
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          cd frontend
          npm install # Change to yarn install if using Yarn

      - name: Build project
        run: |
          cd frontend
          npm run build # Ensure this generates the correct output folder
          
      - name: Deploy using npm script
        run: |
          cd frontend
          npm run deploy # This should push to gh-pages (configured in package.json)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to GitHub Pages
        uses: rayluo/github-pages-overwriter@v1.3
        with:
          source-directory: frontend/dist  # Ensure this matches your build output
          target-branch: gh-pages
