name: Your github action

on:
  push:
    branches:
      - main # Change this if needed

jobs:
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        # You may use a newer version of https://github.com/actions/checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install # Change to yarn install if using Yarn

      - name: Build project
        run: npm run build # Ensure this generates the correct output folder

      - name: Deploy using npm script
        run: npm run deploy # This should push to gh-pages (configured in package.json)

      - name: Generate your content
        run: echo "Optional placeholder. Put your project's static website generator command here."

      - name: Publish current workdir (which contains generated content) to GitHub Pages
        uses: rayluo/github-pages-overwriter@v1.3

        with:

          # Optional.
          #
          # Default value "." means the root directory of your project will be published.
          #
          # You can use whatever directory your project uses,
          # for example "wwwroot" (without leading "./").
          # Such a directory does *not* have to already exist in your repo,
          # it could be an output directory created dynamically
          # by your static website builder.
          source-directory: ./frontend

          # Optional. Default value "gh-pages".
          # It specifies the temporary branch which hosts the static website.
          # Each build will REMOVE this branch and replace it with new content.
          # (If you want to keep your old "gh-pages" branch,
          # you should define a different target branch for this GPO action to work with.)
          target-branch: gh-pages
